dependencies:
  - uniswap/v3-periphery@1.0.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@uniswap=uniswap/v3-periphery@1.0.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env

networks:
  default: cl-hack